// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTnxS0sh6VQAdbrKzfzg_bMWE08ouXxCI',
    appId: '1:143994695294:web:1a14b70cf37dd6e191f22f',
    messagingSenderId: '143994695294',
    projectId: 'car-rental-wandidev',
    authDomain: 'car-rental-wandidev.firebaseapp.com',
    storageBucket: 'car-rental-wandidev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaUWD949SgWtlVJa3iwHVRYyUUQndRgGY',
    appId: '1:143994695294:android:fe4baf3152eceb4791f22f',
    messagingSenderId: '143994695294',
    projectId: 'car-rental-wandidev',
    storageBucket: 'car-rental-wandidev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPA2Wlb6SR6WaR4LghExwMGtG7VGjeP0',
    appId: '1:143994695294:ios:c6bb4158c0fb067691f22f',
    messagingSenderId: '143994695294',
    projectId: 'car-rental-wandidev',
    storageBucket: 'car-rental-wandidev.firebasestorage.app',
    iosBundleId: 'com.wandidev.carRentalApp',
  );
}
